# permissions for end users to view teams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: team-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: team-operator
    app.kubernetes.io/part-of: team-operator
    app.kubernetes.io/managed-by: kustomize
  name: team-viewer-role
rules:
- apiGroups:
  - team.snappcloud.io
  resources:
  - teams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - team.snappcloud.io
  resources:
  - teams/status
  verbs:
  - get
